### ISSUE TITLE
Error when image without face is uploaded

### ISSUE THREAD

**Issue by dilithjay** [h2oai/wave-image-styler#14]
```
Unhandled exception
Traceback (most recent call last):
  File "/home/dilith/Projects/wave-image-styler/.venv/lib/python3.7/site-packages/h2o_wave/server.py", line 320, in _process
    await self._handle(q)
  File "./img_styler/ui/app.py", line 34, in serve
    await handle_on(q)
  File "./img_styler/ui/wave_next.py", line 72, in handle_on
    if await _match_predicate(predicate, func, arity, q, arg_value):
  File "./img_styler/ui/wave_next.py", line 22, in _match_predicate
    await _invoke_handler(func, arity, q, arg)
  File "/home/dilith/Projects/wave-image-styler/.venv/lib/python3.7/site-packages/h2o_wave/routing.py", line 117, in _invoke_handler
    await func(q)
  File "./img_styler/ui/handlers.py", line 213, in on_task_selection
    await process(q)
  File "./img_styler/ui/handlers.py", line 137, in process
    await image_upload(q)
  File "./img_styler/ui/handlers.py", line 268, in image_upload
    facial_feature_analysis(q, local_path, "Uploaded Image")
  File "./img_styler/ui/handlers.py", line 384, in facial_feature_analysis
    logger.info(f"Facial Attributes: {obj}")
UnboundLocalError: local variable 'obj' referenced before assignment
```

**Comment by pramitchoudhary** [comment]
So, as we extend the Studio, if we don't have any faces then maybe we just allow the image to be uploaded without any annotation?

**Comment by pramitchoudhary** [comment]
Done.
